((nil . ((fill-column . 80)))
 (c-mode . ((c-file-style . "GNU")
	    (eval . (global-ede-mode))
	    (eval . (semantic-mode))	    
	    (eval . (global-semanticdb-minor-mode))
	    (eval . (global-semantic-mru-bookmark-mode))
	    (eval . (global-semantic-highlight-func-mode))
	    (eval . (global-semantic-stickyfunc-mode))
	    (eval . (global-semantic-decoration-mode))
	    (eval . (global-semantic-idle-local-symbol-highlight-mode))
	    (eval . (global-semantic-idle-scheduler-mode))
	    (eval . (global-semantic-idle-completions-mode))
	    (eval . (global-semantic-idle-summary-mode)))))
