name: build-test-password-cli-manager
on: [push]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt install -y gcc autoconf autotools-dev autoconf-archive
      - run: |
          chmod +x ./bootstrap
          ./bootstrap
          make
          make check
        shell: bash
